version: '3.8'

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      driver: "none"

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    logging:
      driver: "none"

  elasticsearch:
    image: elasticsearch:8.18.1
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - path.repo=/snapshots
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ports:
      - "9201:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - ./backups/es/snapshot:/snapshots
    logging:
      driver: "none"
    
  kibana:
    image: kibana:8.18.1
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    ports:
      - "56012:5601"
    volumes:
      - ./backups/es/snapshot:/snapshots
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601/status"]
      interval: 10s
      timeout: 5s
      retries: 30
    logging:
      driver: "none"

  django:
    build:
      context: ./
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8010:8000"
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    depends_on:
      elasticsearch:
        condition: service_healthy
      db:
        condition: service_started
      redis:
        condition: service_started
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/db
      - REDIS_URL=redis://redis:6379/0
      - ELASTIC_URL=http://elasticsearch:9200

volumes:
  postgres_data:
  redis_data:
  es_data:
